version: "3.8"

services:
  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: ftp-test
    restart: unless-stopped
    environment:
      PUBLICHOST: "127.0.0.1"
      FTP_USER_NAME: "admin"
      FTP_USER_PASS: "wed892000"
      FTP_USER_HOME: "/home/admin"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
